// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCMvTJUqPb2gu3maDAR4SFEVE0LGQxMg',
    appId: '1:493827717247:web:58eafa8bf6d9b75ae0674a',
    messagingSenderId: '493827717247',
    projectId: 'flutter-x-firebase-3d42a',
    authDomain: 'flutter-x-firebase-3d42a.firebaseapp.com',
    storageBucket: 'flutter-x-firebase-3d42a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwb1QqpfeTiXYdGlPm3kRuH8YdwxiWXG0',
    appId: '1:493827717247:android:a7c74b850a6f7007e0674a',
    messagingSenderId: '493827717247',
    projectId: 'flutter-x-firebase-3d42a',
    storageBucket: 'flutter-x-firebase-3d42a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgH-QFo1iwpnsXKDtKKD96DpO6GweZV4k',
    appId: '1:493827717247:ios:acc415969609c298e0674a',
    messagingSenderId: '493827717247',
    projectId: 'flutter-x-firebase-3d42a',
    storageBucket: 'flutter-x-firebase-3d42a.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgH-QFo1iwpnsXKDtKKD96DpO6GweZV4k',
    appId: '1:493827717247:ios:acc415969609c298e0674a',
    messagingSenderId: '493827717247',
    projectId: 'flutter-x-firebase-3d42a',
    storageBucket: 'flutter-x-firebase-3d42a.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoCMvTJUqPb2gu3maDAR4SFEVE0LGQxMg',
    appId: '1:493827717247:web:b69def411070e3a9e0674a',
    messagingSenderId: '493827717247',
    projectId: 'flutter-x-firebase-3d42a',
    authDomain: 'flutter-x-firebase-3d42a.firebaseapp.com',
    storageBucket: 'flutter-x-firebase-3d42a.firebasestorage.app',
  );
}
